import java.security.MessageDigest

plugins {
	id("checkstyle")
	id("java-library")
	id("jacoco")
	id("com.vanniktech.maven.publish") version "0.36.0"
	id("net.kyori.blossom") version "2.2.0"
}

group = "org.mockbukkit.mockbukkit"
version = getFullVersion()

repositories {
	mavenCentral()
	maven("https://hub.spigotmc.org/nexus/content/repositories/public/")
	maven("https://repo.md-5.net/content/groups/public/")
	maven("https://repo.papermc.io/repository/maven-public/")
}

dependencies {
	// Paper API - compileOnly + testImplementation to avoid snapshot issues in Maven Central
	compileOnly("io.papermc.paper:paper-api:${property("paper.api.full-version")}")
	testImplementation("io.papermc.paper:paper-api:${property("paper.api.full-version")}")

	api("org.jetbrains:annotations:26.1.0")
	api("org.hamcrest:hamcrest:3.0")

	// Dependencies for Unit Tests
	implementation("org.junit.jupiter:junit-jupiter-api:6.0.3")
	testImplementation(platform("org.junit:junit-bom:6.0.3"))
	testImplementation("org.junit.jupiter:junit-jupiter")
	testRuntimeOnly("org.junit.platform:junit-platform-launcher")
	testImplementation("org.skyscreamer:jsonassert:1.5.3")

	// General utilities for the project
	implementation("net.kyori:adventure-platform-bungeecord:4.4.1") {
		exclude("net.kyori", "adventure-platform-api")
		exclude("net.kyori", "adventure-api")
	}

	implementation("net.bytebuddy:byte-buddy:1.18.8")

	compileOnly("org.projectlombok:lombok:1.18.44")
	annotationProcessor("org.projectlombok:lombok:1.18.44")
	testCompileOnly("org.projectlombok:lombok:1.18.44")
	testAnnotationProcessor("org.projectlombok:lombok:1.18.44")

	// LibraryLoader dependencies
	implementation("org.apache.maven:maven-resolver-provider:3.8.5")
	implementation("org.apache.maven.resolver:maven-resolver-connector-basic:1.9.18")
	implementation("org.apache.maven.resolver:maven-resolver-transport-http:1.9.18")
}

tasks {
	jar {
		manifest {
			attributes(
				"Automatic-Module-Name" to "org.mockbukkit.mockbukkit",
				"Paper-Version" to project.property("paper.api.full-version").toString(),
				"Paper-API-Version" to project.property("paper.api.version").toString(),
				"MockBukkit-Version" to getFullVersion()
			)
		}
	}

	java {
		withSourcesJar()
	}

	compileJava {
		options.compilerArgs.addAll(listOf("-Xlint:-deprecation", "-Xlint:-removal"))
	}

	compileTestJava {
		options.compilerArgs.addAll(listOf("-Xlint:-deprecation", "-Xlint:-removal"))
	}

	javadoc {
		options {
			(options as? StandardJavadocDocletOptions)?.apply {
				encoding = "UTF-8"
				tags(
					"apiNote:a:API Note:",
					"implSpec:a:Implementation Requirements:",
					"implNote:a:Implementation Note:"
				)
				// Custom options
				addBooleanOption("Xdoclint:all,-missing", true)
				links("https://jd.papermc.io/paper/${(project.property("paper.api.full-version") as String).split('-')[0]}/")
			}
		}
	}

	publishToMavenLocal {
		doLast {
			println("Published to Maven local with version $version")
		}
	}

	test {
		dependsOn(project(":extra:TestPlugin").tasks.jar)
		useJUnitPlatform()
	}

	check {
		dependsOn(jacocoTestReport)
	}

	jacocoTestReport {
		dependsOn(test)
		reports {
			xml.required.set(true)
			html.required.set(true)
			html.outputLocation.set(layout.buildDirectory.dir("jacocoHtml"))
		}
	}

	jacoco {
		toolVersion = "0.8.14"
	}

	register("updateResources") {
		dependsOn(":metaminer:runServer")
		doLast {
			copy {
				from("./metaminer/run/plugins/MetaMiner")
				into(".")
			}
		}
	}

	register("printPaperDetails")
	{
		doLast {
			val dependency = getDependencyInformation(
				dependencyGroup = "io.papermc.paper",
				artifactName = "paper-api",
				artifactVersion = project.property("paper.api.full-version").toString()
			)
			println("Paper version: ${project.property("paper.api.version")}")
			println("Paper full version: ${project.property("paper.api.full-version")}")
			println("Paper resolved version: ${dependency?.resolvedVersion}")
			println("Paper SHA-512: ${dependency?.hash}")
		}
	}
}

sourceSets {
	main {
		blossom {
			javaSources {
				property("mockBukkitVersion", getFullVersion())
				property("paperApiFullVersion", project.property("paper.api.full-version").toString())
				property("paperApiVersion", project.property("paper.api.version").toString())
				property("buildTime", System.currentTimeMillis().toString())
				property("branch", run("git", "rev-parse", "--abbrev-ref", "HEAD"))
				property("commit", run("git", "rev-parse", "HEAD"))
				val buildNumber = System.getenv("GITHUB_RUN_NUMBER")
				if (buildNumber != null) {
					property("buildNumber", buildNumber)
				} else {
					property("buildNumber", "")
				}
			}
		}
		resources {
			srcDir("src/main/resources-autogenerated")
		}
	}
	test {
		resources {
			srcDir("src/test/resources-autogenerated")
		}
	}
}

java {
	toolchain {
		languageVersion.set(JavaLanguageVersion.of(property("java.version").toString().toInt()))
	}
}

mavenPublishing {
	coordinates(project.group.toString(), "mockbukkit-v${property("paper.api.version")}", project.version.toString())

	pom {
		description.set("MockBukkit is a mocking framework for bukkit to allow the easy unit testing of Bukkit plugins.")
		name.set("MockBukkit-v${property("paper.api.version")}")
		url.set("https://github.com/MockBukkit/MockBukkit")
		licenses {
			license {
				name.set("MIT License")
				url.set("https://github.com/MockBukkit/MockBukkit/blob/v${property("paper.api.version")}/LICENSE")
			}
		}
		developers {
			developer {
				id.set("seeseemelk")
				name.set("Sebastiaan de Schaetzen")
				email.set("sebastiaan.de.schaetzen@gmail.com")
			}
			developer {
				id.set("thebusybiscuit")
				name.set("TheBusyBiscuit")
			}
			developer {
				id.set("insprill")
				name.set("Pierce Thompson")
				email.set("pierce@insprill.net")
			}
			developer {
				id.set("thelooter")
				name.set("Eve Kolb")
				email.set("me@thelooter.de")
			}
			developer {
				id.set("thorinwasher")
				name.set("Hjalmar Gunnarsson")
				email.set("officialhjalmar.gunnarsson@outlook.com")
			}
			developer {
				id.set("4everTheOne")
				name.set("Afonso Oliveira")
			}
		}
		scm {
			connection.set("scm:git:git://github.com/MockBukkit/MockBukkit.git")
			developerConnection.set("scm:git:ssh://github.com:MockBukkit/MockBukkit.git")
			url.set("https://github.com/MockBukkit/MockBukkit/tree/v${property("paper.api.version")}")
		}
	}
	publishToMavenCentral(true)
	// No key available to sign with for maven local
	if (!project.gradle.startParameter.taskNames.any { it.contains("publishToMavenLocal") }) {
		signAllPublications()
	}
}

fun isAction(): Boolean {
	return System.getenv("GITHUB_ACTIONS") == "true" && System.getenv("GITHUB_REPOSITORY") == "MockBukkit/MockBukkit"
}

fun getFullVersion(): String {
	return if (isAction()) {
		property("mockbukkit.version") as String
	} else {
		"dev-${run("git", "rev-parse", "--verify", "--short", "HEAD")}"
	}
}

fun run(vararg cmd: String): String {
	return providers.exec {
		commandLine(*cmd)
	}.standardOutput.asText.get().trim()
}

/**
 * Computes the cryptographic hash of a resolved dependency artifact within a specified Gradle configuration.
 *
 * This method locates the target dependency in the resolved artifacts of the given configuration,
 * then streams the artifact file to compute its hash using the specified algorithm.
 *
 * @param dependencyGroup 		The group ID of the dependency (e.g., "org.jetbrains.kotlin").
 * @param artifactName 			The name of the dependency artifact (e.g., "kotlin-stdlib").
 * @param artifactVersion 		The version of the dependency (e.g., "1.9.0").
 * @param hashAlgorithm 		The hashing algorithm to use (default: "SHA-512").
 *                      		Common values include "SHA-256", "SHA-1", and "MD5".
 * @param targetConfiguration 	The name of the Gradle configuration to resolve from (default: "compileClasspath").
 *
 * @return The hexadecimal string representation of the computed hash, or `null` if the artifact
 *         could not be found or the hash computation failed.
 */
fun Project.getDependencyInformation(
	dependencyGroup: String,
	artifactName: String,
	artifactVersion: String,
	hashAlgorithm: String = "SHA-512",
	targetConfiguration: String = "compileClasspath"
): DependencyHashResult? {
	val artifact = try {
		configurations.getByName(targetConfiguration)
			.resolvedConfiguration
			.resolvedArtifacts
			.firstOrNull {
				val id = it.moduleVersion.id
				id.group == dependencyGroup &&
						id.name == artifactName &&
						id.version == artifactVersion
			} ?: run {
			logger.warn("Artifact not found: $dependencyGroup:$artifactName:$artifactVersion in configuration '$targetConfiguration'")
			return null
		}
	} catch (e: Exception) {
		logger.warn("Failed to resolve configuration '$targetConfiguration': ${e.message}")
		return null
	}

	val resolvedVersion = artifact.id.componentIdentifier.displayName
	val hash = try {
		val digest = MessageDigest.getInstance(hashAlgorithm)
		artifact.file.inputStream().buffered(DEFAULT_BUFFER_SIZE).use { input ->
			val buffer = ByteArray(DEFAULT_BUFFER_SIZE)
			while (true) {
				val bytesRead = input.read(buffer)
				if (bytesRead == -1) {
					break
				}
				digest.update(buffer, 0, bytesRead)
			}
		}
		digest.digest().joinToString("") { "%02x".format(it) }
	} catch (e: Exception) {
		logger.error("Failed to compute digest for ${artifact.file.name}: ${e.message}")
		return null
	}

	return DependencyHashResult(hash = hash, resolvedVersion = resolvedVersion)
}

data class DependencyHashResult(
	val hash: String,
	val resolvedVersion: String
)
