package org.mockbukkit.metaminer;

import org.apache.commons.io.FileUtils;
import org.bukkit.plugin.java.JavaPlugin;
import org.mockbukkit.metaminer.internal.MaterialDataGenerator;
import org.mockbukkit.metaminer.internal.potion.PotionDataGenerator;
import org.mockbukkit.metaminer.keyed.KeyedDataGenerator;
import org.mockbukkit.metaminer.keyed.RegistryKeyClassDataGenerator;
import org.mockbukkit.metaminer.recipes.RecipeDataGenerator;
import org.mockbukkit.metaminer.tags.TagDataGenerator;
import org.mockbukkit.metaminer.tests.BlockDataGenerator;
import org.mockbukkit.metaminer.tests.BlockStateGenerator;
import org.mockbukkit.metaminer.tests.ItemStackTestDataGenerator;
import org.mockbukkit.metaminer.translation.TranslationDataGenerator;
import org.mockbukkit.metaminer.world.WorldConfigurationGenerator;

import java.io.File;
import java.io.IOException;
import java.util.List;
import java.util.logging.Level;

public class MetaMiner extends JavaPlugin
{

	@Override
	public void onEnable()
	{
		this.getLogger().log(Level.INFO, "Generating data for MockBukkit");
		try
		{
			FileUtils.deleteDirectory(this.getDataFolder());
		}
		catch (IOException e)
		{
			throw new RuntimeException(e);
		}
		for (DataGenerator dataGenerator : getDataGenerators())
		{
			try
			{
				dataGenerator.generateData();
			}
			catch (IOException e)
			{
				e.printStackTrace();
				return;
			}
		}
		this.getLogger().log(Level.INFO, "Successfully generated data!");
		this.getLogger().log(Level.INFO, String.format("The files can be found at '%s'", this.getDataFolder().getPath()));
		this.getLogger().log(Level.INFO, "Copy these files with their respective directories over to the MockBukkit resources folder.");
		getServer().shutdown(); // We're done. So just call it quits.
	}

	private List<DataGenerator> getDataGenerators()
	{
		File testFolder = new File(this.getDataFolder(), "src/test/resources-autogenerated");
		File mainFolder = new File(this.getDataFolder(), "src/main/resources-autogenerated");
		return List.of(
				// Sources
				new KeyedDataGenerator(mainFolder),
				new MaterialDataGenerator(mainFolder),
				new PotionDataGenerator(mainFolder),
				new RecipeDataGenerator(mainFolder),
				new RegistryKeyClassDataGenerator(mainFolder),
				new RegistryKeyClassDataGenerator(mainFolder),
				new TagDataGenerator(mainFolder),
				new TranslationDataGenerator(mainFolder),
				// Test
				new BlockStateGenerator(testFolder),
				new BlockDataGenerator(testFolder),
				new WorldConfigurationGenerator(testFolder),
				new ItemStackTestDataGenerator(testFolder)
		);
	}

}
