package org.mockbukkit.metaminer;

import com.google.gson.JsonObject;
import net.kyori.adventure.text.Component;
import org.apache.commons.io.FileUtils;
import org.bukkit.Bukkit;
import org.bukkit.Material;
import org.bukkit.enchantments.Enchantment;
import org.bukkit.inventory.ItemStack;
import org.bukkit.plugin.java.JavaPlugin;
import org.mockbukkit.metaminer.internal.MaterialDataGenerator;
import org.mockbukkit.metaminer.internal.potion.PotionDataGenerator;
import org.mockbukkit.metaminer.internal.tags.InternalTagDataGenerator;
import org.mockbukkit.metaminer.keyed.KeyedDataGenerator;
import org.mockbukkit.metaminer.keyed.RegistryKeyClassDataGenerator;
import org.mockbukkit.metaminer.recipes.RecipeDataGenerator;
import org.mockbukkit.metaminer.tags.TagDataGenerator;
import org.mockbukkit.metaminer.tests.BlockStateGenerator;
import org.mockbukkit.metaminer.tests.ItemStackTestDataGenerator;
import org.mockbukkit.metaminer.translation.TranslationDataGenerator;

import java.io.File;
import java.io.IOException;
import java.util.List;
import java.util.logging.Level;

public class MetaMiner extends JavaPlugin
{

	@Override
	public void onEnable()
	{
		this.getLogger().log(Level.INFO, "Generating data for MockBukkit");

		// --------
		ItemStack itemStack = ItemStack.of(Material.DIAMOND_SWORD);

		itemStack.addEnchantment(Enchantment.SHARPNESS, 5);
		itemStack.addEnchantment(Enchantment.UNBREAKING, 3);

		itemStack.lore(List.of(
			Component.text("This is line 1"),
			Component.text("This is line 2")
		));

		itemStack.editMeta(meta -> {
			meta.displayName(Component.text("My custom display name"));

			meta.setUnbreakable(true);
		});

		JsonObject object = Bukkit.getUnsafe().serializeItemAsJson(itemStack);
		Bukkit.getLogger().warning("Message: " + object.toString());
		// --------

		try
		{
			FileUtils.deleteDirectory(this.getDataFolder());
		}
		catch (IOException e)
		{
			throw new RuntimeException(e);
		}
		for (DataGenerator dataGenerator : getDataGenerators())
		{
			try
			{
				dataGenerator.generateData();
			}
			catch (IOException e)
			{
				e.printStackTrace();
				return;
			}
		}
		this.getLogger().log(Level.INFO, "Successfully generated data!");
		this.getLogger().log(Level.INFO, String.format("The files can be found at '%s'", this.getDataFolder().getPath()));
		this.getLogger().log(Level.INFO, "Copy these files with their respective directories over to the MockBukkit resources folder.");
		getServer().shutdown(); // We're done. So just call it quits.
	}

	private List<DataGenerator> getDataGenerators()
	{
		File testFolder = new File(this.getDataFolder(), "src/test/resources-autogenerated");
		File mainFolder = new File(this.getDataFolder(), "src/main/resources-autogenerated");
		return List.of(
				// Sources
				new InternalTagDataGenerator(mainFolder),
				new KeyedDataGenerator(mainFolder),
				new MaterialDataGenerator(mainFolder),
				new PotionDataGenerator(mainFolder),
				new RecipeDataGenerator(mainFolder),
				new RegistryKeyClassDataGenerator(mainFolder),
				new RegistryKeyClassDataGenerator(mainFolder),
				new TagDataGenerator(mainFolder),
				new TranslationDataGenerator(mainFolder),
				// Test
				new BlockStateGenerator(testFolder),
				new ItemStackTestDataGenerator(testFolder)
		);
	}

}
