mockBukkitVersion=${mockBukkitVersion}
paperApiFullVersion=${paperApiFullVersion}
paperApiVersion=${paperApiVersion}
buildTime=${buildTime}
branch=${branch}
commit=${commit}
buildNumber=${buildNumber}
