name: Build

on:
  pull_request:
    branches: [ v1.* ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Run unit tests
        run: ./gradlew test --refresh-dependencies


  checkstyle:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Validate checkstyle
        run: ./gradlew checkstyleMain checkstyleTest

# Not implemented yet, because Action does not have permission to upload report.
# See PR: https://github.com/MockBukkit/MockBukkit/pull/977
#
#      - name: Comment PR with checkstyle issues
#        uses: jwgmeligmeyling/checkstyle-github-action@master
#        with:
#          path: 'build/reports/checkstyle/**.xml'
#
#    permissions:
#      contents: read # Read repo contents
#      checks: write # Write result from pipeline execution
