name: Check PR has release/* label

on:
  pull_request:
    branches: [ minecraft/v* ]
    types:
      - opened
      - reopened
      - labeled
      - unlabeled
      - synchronize

permissions:
  pull-requests: read

jobs:
  has-release-label:
    runs-on: blacksmith-4vcpu-ubuntu-2404
    timeout-minutes: 10
    steps:
      # agilepathway/pull-request-label-checker v1.6.65
      - uses: docker://agilepathway/pull-request-label-checker@sha256:14f5f3dfda922496d07d53494e2d2b42885165f90677a1c03d600059b7706a61
        id: release-label
        with:
          one_of: release/major,release/minor,release/patch,release/none
          repo_token: ${{ secrets.GITHUB_TOKEN }}
