name: Check PR has release/* label

on:
  pull_request:
    branches: [ minecraft/v* ]
    types:
      - opened
      - reopened
      - labeled
      - unlabeled
      - synchronize

permissions:
  pull-requests: read

jobs:
  has-release-label:
    runs-on: blacksmith-4vcpu-ubuntu-2404
    timeout-minutes: 10
    steps:
      # agilepathway/pull-request-label-checker v1.6.65
      - uses: docker://agilepathway/pull-request-label-checker@sha256:276e6cdbf5ae0a6f5ca6bfb137df0a44bb4f78ad063c0f997329675fe656f4bf
        id: release-label
        with:
          one_of: release/major,release/minor,release/patch,release/none
          repo_token: ${{ secrets.GITHUB_TOKEN }}
