name: Code style

# Run it on any branch.
on: push

jobs:
  formatter:

    name: Format code
    runs-on: ubuntu-latest
    
    # Mak this workflow only run on forks.
    if: github.repository != 'seeseemelk/MockBukkit'

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}

    - name: Install astyle
      run: sudo apt-get install -y astyle
      
    - name: Check formatting
      run: astyle --options=.astylerc '*.java'

    - name: Commit changes
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: 'Auto-update code formatting'
        file_pattern: '*.java'
